---
- name: Install HTTP server
  hosts: node1
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present

  - name: Start Httpd
    service:
      name: httpd
      state: started

  - name: Enable Httpd
    service:
      name: httpd
      enabled: yes 

- name: Deploy Web App
  hosts: node1
  become: yes

  tasks:
  - name: Install GIT
    yum:
      name: git
      state: present

  - name: Host Code
    git:
      repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
      dest: /var/www/html
      force: yes
...

